package:
  name: mintpy_beta_01
  version: 1.156
build:
  number: 0
source:
  url: https://files.pythonhosted.org/packages/ff/8c/cc1b1b751c6ce32532bb204c6d6a03c51a543e1a26ccd4d1a1da3c353d9b/mintpy_beta-meissam-0.0.1.tar.gz
  sha256: d9201c21d5c60e93c08bc13ac972835822071d209b756e3dad112b95f6861515
  md5: b00381011acac788b077b97e77e3735a

requirements:
  build:
    # If your project compiles code (such as a C extension) then add the required compilers as separate entries here.
    # Compilers are named 'c', 'cxx' and 'fortran'.
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
