# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

version: 2

jobs:
  build_linux_64_:
    working_directory: ~/test
    machine: true
    environment:
      - CONFIG: "linux_64_"
      - UPLOAD_PACKAGES: "True"
        DOCKER_IMAGE: "condaforge/linux-anvil-comp7"
    steps:
      - checkout

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_linux_64_
